#### (1) Add code that creates a _list of dictionaries_ called `alphabet_data`

In [2]:
from string import (ascii_lowercase,ascii_uppercase)

In [3]:
alphabet_data = []
lower = ascii_lowercase
upper = ascii_uppercase
index = range(1,27)

In [4]:
for l, u, i in zip(lower, upper, index):
    temp_dict = {'lower': l, 'upper':u ,'index': i}
    alphabet_data.append(temp_dict)

In [5]:
alphabet_data

[{'lower': 'a', 'upper': 'A', 'index': 1},
 {'lower': 'b', 'upper': 'B', 'index': 2},
 {'lower': 'c', 'upper': 'C', 'index': 3},
 {'lower': 'd', 'upper': 'D', 'index': 4},
 {'lower': 'e', 'upper': 'E', 'index': 5},
 {'lower': 'f', 'upper': 'F', 'index': 6},
 {'lower': 'g', 'upper': 'G', 'index': 7},
 {'lower': 'h', 'upper': 'H', 'index': 8},
 {'lower': 'i', 'upper': 'I', 'index': 9},
 {'lower': 'j', 'upper': 'J', 'index': 10},
 {'lower': 'k', 'upper': 'K', 'index': 11},
 {'lower': 'l', 'upper': 'L', 'index': 12},
 {'lower': 'm', 'upper': 'M', 'index': 13},
 {'lower': 'n', 'upper': 'N', 'index': 14},
 {'lower': 'o', 'upper': 'O', 'index': 15},
 {'lower': 'p', 'upper': 'P', 'index': 16},
 {'lower': 'q', 'upper': 'Q', 'index': 17},
 {'lower': 'r', 'upper': 'R', 'index': 18},
 {'lower': 's', 'upper': 'S', 'index': 19},
 {'lower': 't', 'upper': 'T', 'index': 20},
 {'lower': 'u', 'upper': 'U', 'index': 21},
 {'lower': 'v', 'upper': 'V', 'index': 22},
 {'lower': 'w', 'upper': 'W', 'index': 23},
 {'lower': 'x', 'upper': 'X', 'index': 24},
 {'lower': 'y', 'upper': 'Y', 'index': 25},
 {'lower': 'z', 'upper': 'Z', 'index': 26}]

#### (2) `import pandas as pd` and cast `alphabet_data` to a DataFrame:

In [9]:
import pandas as pd
alphabet_df = pd.DataFrame(alphabet_data)
alphabet_df.set_index('index', inplace=True)

In [10]:
alphabet_df

      lower upper
index
1         a     A
2         b     B
3         c     C
4         d     D
5         e     E
6         f     F
7         g     G
8         h     H
9         i     I
10        j     J
11        k     K
12        l     L
13        m     M
14        n     N
15        o     O
16        p     P
17        q     Q
18        r     R
19        s     S
20        t     T
21        u     U
22        v     V
23        w     W
24        x     X
25        y     Y
26        z     Z